WebsiteMVC/WebsiteMVC/Controllers/QuyController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebsiteMVC.Models;

namespace WebsiteMVC.Controllers
{
    public class QuyController : BaseController
    {
        private QLTCEntities db = new QLTCEntities();

        // GET: Quy
        public ActionResult Index(string stimeStart, string stimeEnd)
        {
            DateTime timeEnd = DateTime.Now;
            DateTime timeStart = timeEnd.Subtract(TimeSpan.FromDays(30));
            if (DateTime.TryParse(stimeStart, out timeStart) == false) timeStart = timeEnd.Subtract(TimeSpan.FromDays(30));
            if (DateTime.TryParse(stimeEnd, out timeEnd) == false) timeEnd = DateTime.Now;
            timeEnd = new DateTime(timeEnd.Year, timeEnd.Month, timeEnd.Day, 23, 59, 59);
            ViewBag.timeStart = timeStart.ToString("yyyy-MM-dd");
            ViewBag.timeEnd = timeEnd.ToString("yyyy-MM-dd");

            var data = new List<TangGiam>();

            data.AddRange((from congno in db.CongNoes.Where(q => q.CreateTime >= timeStart && q.CreateTime <= timeEnd && q.State != Notify.CANCLE)
                           select new TangGiam
                           {
                               Time = congno.CreateTime,
                               Thu = congno.MaCongNo.StartsWith("NO_") ? congno.SoTien : 0,
                               Chi = congno.MaCongNo.StartsWith("CONG_") ? congno.SoTien : 0,
                           }));

            data.AddRange((from thuchi in db.ThuChis.Where(q => q.CreateTime >= timeStart && q.CreateTime <= timeEnd && q.State != Notify.CANCLE)
                           select new TangGiam
                           {
                               Time = thuchi.CreateTime,
                               Thu = thuchi.MaThuChi.StartsWith("THU") ? thuchi.SoTien : 0,
                               Chi = thuchi.MaThuChi.StartsWith("CHI") ? thuchi.SoTien : 0,
                           }
                           ));

            data.AddRange((from thuchi in db.TamUngs.Where(q => q.CreateTime >= timeStart && q.CreateTime <= timeEnd && q.State != Notify.CANCLE)
                           select new TangGiam
                           {
                               Time = thuchi.CreateTime,
                               Thu = 0,
                               Chi = thuchi.SoTienDaUng
                           }));

            var gr = data.GroupBy(q => new DateTime(q.Time.Value.Year, q.Time.Value.Month, 1));
            string d = "[";
            bool first = true;
            for (DateTime date = new DateTime(timeStart.Year, timeStart.Month, 1); date <= timeEnd; date = date.AddMonths(1))
            {
                d += $"{(first ? "" : ",")}['{date.ToString("MM/yyyy")}',{gr.FirstOrDefault(q => q.Key == date)?.Sum(q => q.Thu) ?? 0},{gr.FirstOrDefault(q => q.Key == date)?.Sum(q => q.Chi) ?? 0}]";
                first = false;
            }
            d += "]";
            ViewBag.data = d;
            return View(db.Quys.Where(q => q.State != Notify.CANCLE));
        }

        // GET: Quy/Edit/5
        public ActionResult Edit(int? id)
        {
            Quy obj = new Quy();
            if (id > 0)
            {
                obj = db.Quys.Find(id);
            }
            return View(obj);
        }

        // POST: Quy/Edit/5
        [HttpPost]
        public ActionResult Edit(Quy obj)
        {
            if (obj.IDQuy > 0)
            {
                db.Entry(obj).State = EntityState.Modified;
            }
            else
            {
                obj.State = Notify.INIT;
                obj.CreateBy = Account.IDTaiKhoan;
                obj.CreateTime = DateTime.Now;
                db.Quys.Add(obj);
            }
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // POST: Quy/Delete/5
        public JsonResult Delete(int id)
        {
            Quy obj = db.Quys.Find(id);
            obj.State = Notify.CANCLE;
            return Json(db.SaveChanges());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        public JsonResult State(int id, byte state)
        {
            db.Quys.Find(id).State = state;
            return Json(db.SaveChanges() > 0);
        }
    }

    public class TangGiam
    {
        public decimal? Thu { get; set; }
        public decimal? Chi { get; set; }
        public DateTime? Time { get; set; }
    }
}

WebsiteMVC/WebsiteMVC/Views/Shared/_LayoutAdminEdit.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAmin.cshtml";
}
<div class="panel panel-default">
    <div class="panel-heading"><i class="fa fa-pencil"></i> @ViewBag.Title</div>
    <div class="panel-body">
        @RenderBody()
        <a href="@Url.Action("Index")" class="btn btn-default"><i class="fa fa-arrow-circle-o-left"></i> QUAY LẠI DANH SÁCH</a>
    </div>
</div>

WebsiteMVC/WebsiteMVC/Views/Shared/_LayoutAdminList.cshtml
@{
    Layout = "~/Views/Shared/_LayoutAmin.cshtml";
}

<div class="portlet box blue">
    <div class="portlet-title">
        <div class="caption">
            <i class="fa fa-edit"></i>@ViewBag.Title
        </div>
    </div>
    <div class="portlet-body">
        @RenderBody()
    </div>
</div>



@section css{
    <link href="/Content/theme/assets/global/plugins/datatables/media/css/jquery.dataTables.min.css" rel="stylesheet" />
}

@section js{
    <script type="text/javascript" src="/Content/theme/assets/global/plugins/datatables/media/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="/Content/theme/assets/global/plugins/datatables/plugins/bootstrap/dataTables.bootstrap.js"></script>

    <script>
        $("#table").DataTable({
            'rowsGroup': [0]
        });

        function delete_object(target, id) {
            if (confirm("Bạn có muốn xóa không?")) {
                $.ajax({
                    url: "@Url.Action("Delete")",
                    type: "POST",
                    data: { id: id },
                    success: function (d) {
                        if (d) {
                            $(target).closest("tr").remove();
                        } else {
                            alert("Xóa thất bại");
                        }
                    }
                })
            }
        }
    </script>
}

WebsiteMVC/WebsiteMVC/Views/Shared/_LayoutAmin.cshtml
<!DOCTYPE html>
<!--
Template Name: Metronic - Responsive Admin Dashboard Template build with Twitter Bootstrap 3.3.5
Version: 4.1.0
Author: KeenThemes
Website: http://www.keenthemes.com/
Contact: support@keenthemes.com
Follow: www.twitter.com/keenthemes
Like: www.facebook.com/keenthemes
Purchase: http://themeforest.net/item/metronic-responsive-admin-dashboard-template/4021469?ref=keenthemes
License: You must have a valid license purchased only from themeforest(the above link) in order to legally use the theme for your project.
-->
<!--[if IE 8]> <html lang="en" class="ie8 no-js"> <![endif]-->
<!--[if IE 9]> <html lang="en" class="ie9 no-js"> <![endif]-->
<!--[if !IE]><!-->
<html lang="en">
<!--<![endif]-->
<!-- BEGIN HEAD -->
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title - ADMIN</title>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta content="width=device-width, initial-scale=1.0" name="viewport" />
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta content="" name="description" />
    <meta content="" name="author" />
    <!-- BEGIN GLOBAL MANDATORY STYLES -->
    <link href="http://fonts.googleapis.com/css?family=Open+Sans:400,300,600,700&subset=all" rel="stylesheet" type="text/css" />
    <link href="/Content/theme/assets/global/plugins/font-awesome/css/font-awesome.min.css" rel="stylesheet" type="text/css" />
    <link href="/Content/theme/assets/global/plugins/simple-line-icons/simple-line-icons.min.css" rel="stylesheet" type="text/css" />
    <link href="/Content/theme/assets/global/plugins/bootstrap/css/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <link href="/Content/theme/assets/global/plugins/uniform/css/uniform.default.css" rel="stylesheet" type="text/css" />
    <link href="/Content/theme/assets/global/plugins/bootstrap-switch/css/bootstrap-switch.min.css" rel="stylesheet" type="text/css" />
    <!-- END GLOBAL MANDATORY STYLES -->
    <!-- BEGIN THEME STYLES -->
    <link href="/Content/theme/assets/global/css/components.css" id="style_components" rel="stylesheet" type="text/css" />
    <link href="/Content/theme/assets/global/css/plugins.css" rel="stylesheet" type="text/css" />
    <link href="/Content/theme/assets/admin/layout/css/layout.css" rel="stylesheet" type="text/css" />
    <link id="style_color" href="/Content/theme/assets/admin/layout/css/themes/darkblue.css" rel="stylesheet" type="text/css" />
    <link href="/Content/theme/assets/admin/layout/css/custom.css" rel="stylesheet" type="text/css" />
    <!-- END THEME STYLES -->
    <link rel="shortcut icon" href="~/Content/Upload/img/lightJSC.png" />
    <script src="/Content/theme/assets/global/plugins/jquery.min.js" type="text/javascript"></script>
    @RenderSection("css", false)
</head>
<!-- END HEAD -->
<!-- BEGIN BODY -->
<!-- DOC: Apply "page-header-fixed-mobile" and "page-footer-fixed-mobile" class to body element to force fixed header or footer in mobile devices -->
<!-- DOC: Apply "page-sidebar-closed" class to the body and "page-sidebar-menu-closed" class to the sidebar menu element to hide the sidebar by default -->
<!-- DOC: Apply "page-sidebar-hide" class to the body to make the sidebar completely hidden on toggle -->
<!-- DOC: Apply "page-sidebar-closed-hide-logo" class to the body element to make the logo hidden on sidebar toggle -->
<!-- DOC: Apply "page-sidebar-hide" class to body element to completely hide the sidebar on sidebar toggle -->
<!-- DOC: Apply "page-sidebar-fixed" class to have fixed sidebar -->
<!-- DOC: Apply "page-footer-fixed" class to the body element to have fixed footer -->
<!-- DOC: Apply "page-sidebar-reversed" class to put the sidebar on the right side -->
<!-- DOC: Apply "page-full-width" class to the body element to have full width page without the sidebar menu -->
<body class="page-header-fixed page-quick-sidebar-over-content">
    <!-- BEGIN HEADER -->
    <div class="page-header navbar navbar-fixed-top">
        <!-- BEGIN HEADER INNER -->
        <div class="page-header-inner">
            <!-- BEGIN LOGO -->
            <div class="page-logo">
                <a href="/">
                    <img src="~/Content/Upload/img/lightJSC.png" alt="logo" class="logo-default" style="max-height: 40px"/>
                </a>
                <div class="menu-toggler sidebar-toggler hide">
                    <!-- DOC: Remove the above "hide" to enable the sidebar toggler button on header -->
                </div>
            </div>
            <!-- END LOGO -->
            <!-- BEGIN RESPONSIVE MENU TOGGLER -->
            <a href="javascript:;" class="menu-toggler responsive-toggler" data-toggle="collapse" data-target=".navbar-collapse">
            </a>
            <!-- END RESPONSIVE MENU TOGGLER -->
            <!-- BEGIN TOP NAVIGATION MENU -->
            @Html.Partial("_TopMenu")
            <!-- END TOP NAVIGATION MENU -->
        </div>
        <!-- END HEADER INNER -->
    </div>
    <!-- END HEADER -->
    <div class="clearfix">
    </div>
    <!-- BEGIN CONTAINER -->
    <div class="page-container">
        <!-- BEGIN SIDEBAR -->
        <div class="page-sidebar-wrapper">
            <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
            <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
            <div class="page-sidebar navbar-collapse collapse">
                <!-- BEGIN SIDEBAR MENU -->
                <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
                <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
                <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
                <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
                <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
                <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
                @Html.Partial("_Menu")
                <!-- END SIDEBAR MENU -->
            </div>
        </div>
        <!-- END SIDEBAR -->
        <!-- BEGIN CONTENT -->
        <div class="page-content-wrapper">
            <div class="page-content">
                <!-- BEGIN SAMPLE PORTLET CONFIGURATION MODAL FORM-->
                <div class="modal fade" id="portlet-config" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
                    <div class="modal-dialog">
                        <div class="modal-content">
                            <div class="modal-header">
                                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                                <h4 class="modal-title">Modal title</h4>
                            </div>
                            <div class="modal-body">
                                Widget settings form goes here
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn blue">Save changes</button>
                                <button type="button" class="btn default" data-dismiss="modal">Close</button>
                            </div>
                        </div>
                        <!-- /.modal-content -->
                    </div>
                    <!-- /.modal-dialog -->
                </div>
                <!-- /.modal -->
                <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
                <!-- BEGIN PAGE CONTENT-->
                <div class="row">
                    <div class="col-md-12">
                        @RenderBody()
                    </div>
                </div>
                <!-- END PAGE CONTENT-->
            </div>
        </div>
        <!-- END CONTENT -->
    </div>
    <!-- END CONTAINER -->
    <!-- BEGIN FOOTER -->
    <div class="page-footer">
        <div class="page-footer-inner">
            @DateTime.Now.Year &copy; ADMIN
        </div>
        <div class="scroll-to-top">
            <i class="icon-arrow-up"></i>
        </div>
    </div>
    <!-- END FOOTER -->
    <!-- BEGIN JAVASCRIPTS(Load javascripts at bottom, this will reduce page load time) -->
    <!-- BEGIN CORE PLUGINS -->
    <!--[if lt IE 9]>
    <script src="/Content/theme/assets/global/plugins/respond.min.js"></script>
    <script src="/Content/theme/assets/global/plugins/excanvas.min.js"></script>
    <![endif]-->
    <script src="/Content/theme/assets/global/plugins/jquery-migrate.min.js" type="text/javascript"></script>
    <!-- IMPORTANT! Load jquery-ui.min.js before bootstrap.min.js to fix bootstrap tooltip conflict with jquery ui tooltip -->
    <script src="/Content/theme/assets/global/plugins/jquery-ui/jquery-ui.min.js" type="text/javascript"></script>
    <script src="/Content/theme/assets/global/plugins/bootstrap/js/bootstrap.min.js" type="text/javascript"></script>
    <script src="/Content/theme/assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js" type="text/javascript"></script>
    <script src="/Content/theme/assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js" type="text/javascript"></script>
    <script src="/Content/theme/assets/global/plugins/jquery.blockui.min.js" type="text/javascript"></script>
    <script src="/Content/theme/assets/global/plugins/jquery.cokie.min.js" type="text/javascript"></script>
    <script src="/Content/theme/assets/global/plugins/uniform/jquery.uniform.min.js" type="text/javascript"></script>
    <script src="/Content/theme/assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js" type="text/javascript"></script>
    <!-- END CORE PLUGINS -->
    <script src="/Content/theme/assets/global/scripts/metronic.js" type="text/javascript"></script>
    <script src="/Content/theme/assets/admin/layout/scripts/layout.js" type="text/javascript"></script>
    <script src="/Content/theme/assets/admin/layout/scripts/quick-sidebar.js" type="text/javascript"></script>
    <script>
        jQuery(document).ready(function () {
            Metronic.init(); // init metronic core components
            Layout.init(); // init current layout
            QuickSidebar.init(); // init quick sidebar
        });
    </script>
    <!-- END JAVASCRIPTS -->

    @RenderSection("js", false)
</body>
<!-- END BODY -->
</html>

WebsiteMVC/WebsiteMVC/Views/Shared/_Menu.cshtml
<ul class="page-sidebar-menu" data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
    <!-- DOC: To remove the sidebar toggler from the sidebar you just need to completely remove the below "sidebar-toggler-wrapper" LI element -->
    <li class="sidebar-toggler-wrapper">
        <!-- BEGIN SIDEBAR TOGGLER BUTTON -->
        <div class="sidebar-toggler">
        </div>
        <!-- END SIDEBAR TOGGLER BUTTON -->
    </li>
    <!-- DOC: To remove the search box from the sidebar you just need to completely remove the below "sidebar-search-wrapper" LI element -->
    <li>
        <a href="@Url.Action("Index","Home")">
            <i class="fa fa-home"></i>
            <span class="title">TRANG CHỦ</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index","ThuChi")">
            <i class="fa fa-dollar"></i>
            <span class="title">THU CHI</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index","TamUng")">
            <i class="fa fa-fighter-jet"></i>
            <span class="title">TẠM ỨNG</span>
        </a>
    </li>
    <li>
        <a href="@Url.Action("Index","CongNo")">
            <i class="fa fa-cab"></i>
            <span class="title">CÔNG NỢ</span>
        </a>
    </li>
    <li>
        <a href="javascript:;">
            <i class="fa fa-list"></i>
            <span class="title">DANH MỤC</span>
            <span class="arrow "></span>
        </a>
        <ul class="sub-menu">
            <li>
                <a href="@Url.Action("Index","Quy")">
                    <i class="fa fa-credit-card"></i>
                    QUỸ
                </a>
            </li>
            <li>
                <a href="@Url.Action("Index","TaiKhoan")">
                    <i class="fa fa-user"></i>
                    TÀI KHOẢN
                </a>
            </li>
        </ul>
    </li>
</ul>

WebsiteMVC/WebsiteMVC/Views/Shared/_TopMenu.cshtml
@{
    var acc = WebsiteMVC.Models.LoginHelper.GetAccount();
}

<div class="top-menu">
    <ul class="nav navbar-nav pull-right">
        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
        <li class="dropdown dropdown-user">
            <a href="javascript:;" class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown" data-close-others="true">
                <img alt="" class="img-circle" src="@(string.IsNullOrWhiteSpace(acc.Avatar)?"/Content/theme/assets/admin/layout/img/avatar3_small.jpg":acc.Avatar)" />
                <span class="username username-hide-on-mobile">
                    @acc.FullName
                </span>
                <i class="fa fa-angle-down"></i>
            </a>
            <ul class="dropdown-menu dropdown-menu-default">
                <li>
                    <a href="@Url.Action("Edit","TaiKhoan")">
                        <i class="icon-user"></i> Thông tin cá nhân
                    </a>
                </li>
                <li>
                    <a href="@Url.Action("ChangePassword","TaiKhoan")">
                        <i class="icon-envelope-open"></i> Đổi mật khẩu
                    </a>
                </li>
                <li class="divider">
                </li>
                <li>
                    <a href="@Url.Action("Logout","Login", new { Area = ""})">
                        <i class="icon-key"></i> Đăng xuất
                    </a>
                </li>
            </ul>
        </li>
        <!-- END USER LOGIN DROPDOWN -->
        <!-- BEGIN QUICK SIDEBAR TOGGLER -->
        <!-- DOC: Apply "dropdown-dark" class after below "dropdown-extended" to change the dropdown styte -->
        <li class="dropdown dropdown-quick-sidebar-toggler">
            <a href="@Url.Action("Logout","Login", new { Area = ""})" class="dropdown-toggle">
                <i class="icon-logout"></i>
            </a>
        </li>
        <!-- END QUICK SIDEBAR TOGGLER -->
    </ul>
</div>